# default configuration for rps cnn 
seed: 42 # reproducibility 
data_dir: "data"

# image settings
img_size: [128, 128]    # resize because 200x300 takes 2h to run. compare accurancy?
batch_size: 32          # of images processed together
test_size: 0.15         
val_size: 0.15          
augment: true           # image augmentation for training 

models:
  tiny_cnn:
    type: "tiny"
    lr: 0.001
    dropout: 0.3
    epochs: 15
    augment: "basic"          

  small_cnn:
    type: "small"
    lr: 0.0005
    dropout: 0.3
    epochs: 15
    augment: "green_strong"   # stronger aug: replace green bg + flips/rot/etc.

hparam_search:
  model: "small_cnn"
  learning_rates: [0.001, 0.0005]
  dropouts: [0.3]
  batch_sizes: [32]
  max_trials: 2
